# Generated by Django 5.0.4 on 2026-09-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_application', '0003_delete_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('verification_token', models.CharField(max_length=100, unique=True)),
                ('register_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('assignment_status', models.CharField(default='Completed', max_length=50)),
                ('assessment_status', models.CharField(default='Completed', max_length=50)),
                ('assignment_score', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.FloatField(blank=True, null=True)),
                ('certificate_image', models.CharField(blank=True, max_length=500, null=True)),
                ('certificate_status', models.CharField(default='Active', max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_certificates', to='admin_application.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
