# Generated by Django 5.0.4 on 2026-08-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=255, unique=True)),
                ('Course_Fees', models.FloatField(blank=True, null=True)),
                ('Course_Status', models.CharField(default='Active', max_length=30)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
