# Generated by Django 5.0.4 on 2026-09-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_application', '0002_certificate_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
